import { jsPDF } from 'jspdf';

export async function generateReportPDF(reportData: any) {
  const doc = new jsPDF();
  
  // Add company header
  doc.setFontSize(20);
  doc.text('National Mover Bureau', 20, 20);
  doc.setFontSize(14);
  doc.text('Official Moving Company Report', 20, 30);
  
  // Add company details
  doc.setFontSize(12);
  doc.text(`Company: ${reportData.company_name}`, 20, 50);
  doc.text(`DOT Number: ${reportData.dot_number}`, 20, 60);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 70);
  
  // Add risk assessment
  doc.setFontSize(16);
  doc.text('Risk Assessment', 20, 90);
  doc.setFontSize(12);
  doc.text(`Risk Score: ${reportData.risk_score}/10`, 20, 100);
  
  // Add licensing info
  doc.setFontSize(16);
  doc.text('Licensing & Insurance', 20, 120);
  doc.setFontSize(12);
  doc.text(`License Status: ${reportData.license_status}`, 20, 130);
  doc.text(`Insurance Status: ${reportData.insurance_status}`, 20, 140);
  
  // Add complaints and reviews
  doc.setFontSize(16);
  doc.text('Complaints & Reviews', 20, 160);
  doc.setFontSize(12);
  doc.text(`Total Complaints: ${reportData.complaint_count}`, 20, 170);
  doc.text(`BBB Rating: ${reportData.bbb_rating}`, 20, 180);
  
  // Add footer
  doc.setFontSize(10);
  doc.text('This report is generated by National Mover Bureau\'s AI-powered verification system.', 20, 280);
  doc.text('For more information visit: www.nationalmoverbureau.org', 20, 285);
  
  return doc;
}