import { Shield } from 'lucide-react'
import { ICompanyReport } from '../../lib/types'

export const ReportFooter = ({
  currentReport,
}: {
  currentReport: ICompanyReport
}) => (
  <>
    <div className="bg-white rounded-lg shadow-lg p-6 border border-gray-200">
      <div className="flex flex-col md:flex-row items-center justify-center gap-4 text-center">
        <Shield className="w-6 h-6 text-blue-600" />
        <div>
          <p className="text-sm text-gray-600">
            This is an official report generated by National Mover Bureau
            AI-powered verification system. All data is sourced from federal and
            state records, updated daily.
          </p>
          <p className="text-xs text-gray-500 mt-2">
            Report ID: {currentReport?.id?.split('-')[0]} • Generated on{' '}
            {currentReport?.created_at?.slice(0, 10)} • National Mover Bureau ©{' '}
            {new Date().getFullYear()}
          </p>
        </div>
      </div>
    </div>
    <div className="border-t-4 border-gray-900 pt-8 mt-16">
      <div className="bg-gray-50 border-2 border-gray-200 p-6 rounded-lg">
        <div className="flex items-center justify-between mb-4 gap-4 flex-wrap">
          <div className="flex items-center gap-4 flex-wrap">
            <div className="w-12 min-w-12 h-12 bg-blue-900 rounded-lg flex items-center justify-center">
              <Shield className="w-6 h-6 text-white" />
            </div>
            <div>
              <div className="text-lg font-bold text-gray-900">
                NATIONAL MOVER BUREAU
              </div>
              <div className="text-sm text-gray-600">
                Official Moving Company Verification System
              </div>
            </div>
          </div>
          <div className="text-right text-sm text-gray-600 w-full">
            <div className="font-mono font-bold">
              Report ID: {currentReport?.id?.split('-')[0]}
            </div>
            <div>Generated: {currentReport?.created_at?.slice(0, 10)}</div>
            <div>© {new Date().getFullYear()} National Mover Bureau</div>
          </div>
        </div>

        <div className="border-t border-gray-300 pt-4">
          <div className="text-center text-xs text-gray-600">
            <p>
              <strong>OFFICIAL VERIFICATION REPORT:</strong> This is an official
              verification report with comprehensive analysis including all
              available data fields, AI-powered insights, and risk assessment.
              All data is sourced from federal and state records.
            </p>
          </div>
        </div>
      </div>
    </div>
  </>
)
